---
- name: Restart IIS on Windows Server
  hosts: windows_server  # Replace with the hostname or IP address of your Windows server
  gather_facts: no

  tasks:
    - name: Get the current state of the IIS service
      win_service:
        name: W3SVC
      register: iis_service_status

    - name: Display the current IIS service state
      debug:
        var: iis_service_status.state

    - name: Stop IIS service
      win_service:
        name: W3SVC
        state: stopped

    - name: Wait for 10 seconds
      win_shell: Start-Sleep -Seconds 10

    - name: Start IIS service
      win_service:
        name: W3SVC
        state: started
